language: go
install: go get -v github.com/spf13/hugo
script:
- hugo
after_success:
- git clone https://$GIT_USER_ID:$GIT_USER_PW@github.com/$GIT_USER_ID/$TARGET_REPO.git ../blog
- cp -rf ./public/* ../blog/
- cd ../blog
- git config --local user.name "$GIT_USER_ID"
- git config --local user.email "$GIT_EMAIL"
- git config --list
- pwd
- git add *
- git commit -m "rebuilding site `date` from CI"
- git push https://$GIT_USER_ID:$GIT_USER_PW@github.com/$GIT_USER_ID/$TARGET_REPO.git --all
